//def logger = org.apache.log4j.Logger.getLogger("com.funnelback.MyHookScript");
def r = transaction.response;
def facet_labels = [
  "bs" : "Brain Sciences"
  ,"ls" : "Life Sciences"
  ,"ms" : "Medical Sciences"
  ,"phs" : "Population Health Sciences"
  ,"maps" : "Mathematical & Physical Sciences"
  ,"eng" : "Engineering"
  ,"bartlett" : "Bartlett"
  ,"laws" : "Laws"
  ,"shs" : "Social & Historical Sciences"
  ,"ah" : "Arts & Humanities"
  ,"ioe" : "Institute of Education"

  ,"psychiatry" : "Division of Psychiatry"
  ,"pals" : "Division of Psychology & Language Sciences"
  ,"ear" : "Ear Institute"
  ,"icn" : "Institute of Cognitive Neuroscience"
  ,"ion" : "Institute of Neurology"
  ,"ioo" : "Institute of Ophthalmology"
  ,"biosciences" : "Division of Biosciences"
  ,"gatsby" : "Gatsby Computational Neuroscience Unit"
  ,"lmcb" : "Laboratory for Molecular Cell Biology"
  ,"pharmacy" : "School of Pharmacy"
  ,"cancer" : "Cancer Institute"
  ,"dii" : "Divison of Infection & Immunity"
  ,"medicine" : "Division of Medicine"
  ,"surgery" : "Division of Surgery & Interventional Science"
  ,"eastman" : "Eastman Dental Institute"
  ,"medical" : "Medical School"
  ,"wibr" : "Wolfson Institute for Biomedical Research"
  ,"igh" : "Institute for Global Health"
  ,"iwh" : "Institute for Women's Health"
  ,"ics" : "Institute of Cardiovascular Science"
  ,"ich" : "Institute of Child Health"
  ,"ictm" : "Institute of Clinical Trials and Methodology"
  ,"iehc" : "Institute of Epidemiology and Health Care"
  ,"chemistry" : "Chemistry"
  ,"earth" : "Earth Sciences"
  ,"mathematics" : "Mathematics"
  ,"Icn" : "London Centre for Nanotechnology"
  ,"physics" : "Physics & Astronomy"
  ,"sts" : "Science & Technology Studies"
  ,"mssl" : "Space & Climate Physics"
  ,"statistics" : "Statistical Science"
  ,"australia" : "Australia"
  ,"biochemeng" : "Biochemical Engineering"
  ,"chemeng" : "Chemical Engineering"
  ,"cege" : "Civil, Environmental & Geomatic Engineering"
  ,"cs" : "Computer Science"
  ,"eee" : "Electronic & Electrical Engineering"
  ,"msi" : "Management Science & Innovation"
  ,"mecheng" : "Mechanical Engineering"
  ,"mpb" : "Medical Physics & Bioengineering"
  ,"steapp" : "Science, Technology, Engineering & Public Policy"
  ,"scs" : "Security & Crime Science"
  ,"casa" : "Centre for Advanced Spatial Analysis"
  ,"architecture" : "School of Architecture"
  ,"cpm" : "School of Construction & Project Management"
  ,"dpu" : "Development Planning Unit"
  ,"planning" : "School of Planning"
  ,"spacesyntax" : "Space Syntax Laboratory"
  ,"energy" : "Energy Institute"
  ,"iede" : "Institute for Environmental Design & Engineering"
  ,"ish" : "Institute for Sustainable Heritage"
  ,"isr" : "Institute for Sustainable Resources"
  ,"americas" : "Institute of the Americas"
  ,"anthropology" : "Anthropology"
  ,"archaeology" : "Institute of Archaeology"
  ,"economics" : "Economics"
  ,"geography" : "Geography"
  ,"history" : "History"
  ,"hoa" : "History of Art"
  ,"polsci" : "Political Science"
  ,"ssees" : "School of Slavonic & East European Studies"
  ,"english" : "English Language & Literature"
  ,"esps" : "European Social & Political Studies"
  ,"classics" : "Greek & Latin"
  ,"hjs" : "Hebrew & Jewish Studies"
  ,"dis" : "Information Studies"
  ,"philosophy" : "Philosophy"
  ,"selcs" : "School of European Languages, Culture & Society"
  ,"slade" : "Slade School of Fine Art"
]

if (r && r.facets){
  r.facets.each { facet ->
    facet.categories.each { cat ->
      cat.values.each { val ->
        if (facet_labels[val.label]) {val.label = facet_labels[val.label];}
      }
    }
  }
}
